server:
 port: 80
cors:
  originPattern: "http://localhost:8080 , http://localhost"

spring:
  application:
    name: empresa
  datasource:
    url: jdbc:mariadb://localhost:3306/company
    username: root
    password: 123
springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
api:
  security:
    token:
      secret: ${JWT_SECRET:secret-key}
