cors:
  originPattern: "http://localhost:8080"
spring:
  application:
    name: empresa
  datasource:
    url: jdbc:mariadb://localhost:3306/company
    username: root
    password: 123
springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
servlet:
  multipart:
    enabled: true
    file-size-threshold: 2KB
    max-file-size: 200MB
    max-request-size: 215MB
file:
  upload-dir: /home/nata/Documents/empresa/uploads
